Merge Changes to testing and model outputs to main
biggsbenjamin/earlyexitnet pull request #2
Opened 2023-07-26 13:06 UTC by luigirinaldi

### New additions

- `hw_sim.py` file to contain various functions to emulate the hardware behaviour
- `Comparison` class in `test.py` to allow for different exit comparison functions to be evaluated at the same time, while tracking all desired statistics

### Changes

- CLI options to test over a linear range of thresholds and measure the performance
- CLI options to save the final layer output of the model as well as the values of the comparison functions used
- modified the `_forward_training` function in the models to output tensors to speed up inference when testing 

#### Data Analysis

All the code for generating various plots has been moved to a [dedicated branch](/biggsbenjamin/earlyexitnet/tree/data-analysis)

2023-08-01 18:37 UTC, biggsbenjamin requested changes
Happy to go through some of this tomorrow. Great work!

2023-08-07 10:25 UTC, luigirinaldi commented on src/earlyexitnet/cli.py
> +def run_test(datacoll,model,exits,top1_thr,entr_thr,loss_f,args, save_raw = False):
Tried to explain the difference as best I could, let me know if needs improvement

2023-08-07 11:22 UTC, luigirinaldi commented on src/earlyexitnet/cli.py
> +    parser.add_argument('-sr', '--save_raw_softmax', type=bool, default=False, required=False,
Yes, it is some strange behaviour of the bool type arg parser, I changed it so it only check for the presence of the argument or accepts --no-save_raw as a False argument

2023-08-07 11:32 UTC, luigirinaldi commented on src/earlyexitnet/testing_tools/test.py
> +            self.raw_softmax = torch.cat((self.raw_softmax, sft_accum), dim=1) if self.raw_softmax is not None else sft_accum
This is storing the values of the current softmax vector in a variable to be saved to file later

2023-08-07 11:33 UTC, luigirinaldi commented on src/earlyexitnet/testing_tools/test.py
> +            self.raw_layer = None
This sets up the variables to store the raw softmax vectors to be saved to file, the true result variable wasn't being used anymore

2023-08-07 12:27 UTC, luigirinaldi commented on src/earlyexitnet/tools.py
> +        self.val_bins = np.zeros(bins,dtype=np.float64)
Not sure, think this was changed while debugging something and else and was never corrected

2023-08-07 12:34 UTC, luigirinaldi commented on src/earlyexitnet/tools.py
> +            assert len(res_list[0]) == len(lab_list), "AccuTracker: sample size mismatch"
This is because the first dimension of the res_list is of size exit_nums, and the second dimension (the one indexed by [0]) is the size of the batch

2023-08-07 15:25 UTC, luigirinaldi commented on src/earlyexitnet/testing_tools/test.py
> +            for batch, isExit in enumerate(exit_result):
Yes, it infact yields approximately 10% speedup. also using masks to perform computation only on values that are yet to exit

2024-12-18 22:47 UTC, merged